# Generated by Django 4.0.6 on 2022-08-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceRegistrar', '0002_remove_entry_lastcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='DeviceVersion',
        ),
    ]
