# Generated by Django 4.0.6 on 2022-08-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceRegistrar', '0005_rename_location_entry_devicelocation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='Status',
        ),
    ]
