# Generated by Django 4.0.6 on 2022-08-07 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceRegistrar', '0006_remove_entry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='LastContact',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='Status',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
