# Generated by Django 4.0.6 on 2022-08-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceRegistrar', '0007_entry_lastcontact_entry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='LastContact',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='Status',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
