# Generated by Django 4.0.6 on 2022-08-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceRegistrar', '0008_alter_entry_lastcontact_alter_entry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='Id',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, unique=True),
        ),
    ]
