# Generated by Django 4.0.6 on 2022-08-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceRegistrar', '0009_alter_entry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='DeviceVersion',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='DeviceLocation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='entry',
            name='DeviceType',
            field=models.CharField(max_length=20),
        ),
    ]
