# Generated by Django 4.0.6 on 2022-08-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceRegistrar', '0010_entry_deviceversion_alter_entry_devicelocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='RegistrationTime',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
    ]
