# Generated by Django 4.0.6 on 2022-08-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceRegistrar', '0011_entry_registrationtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRegistry',
            fields=[
                ('Id', models.CharField(max_length=17, primary_key=True, serialize=False, unique=True)),
                ('DeviceType', models.CharField(max_length=20)),
                ('DeviceVersion', models.CharField(max_length=20)),
                ('DeviceLocation', models.CharField(max_length=50)),
                ('PrimaryGroup', models.CharField(max_length=50)),
                ('SecondaryGroup', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=4, null=True)),
                ('RegistrationTime', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
