# Generated by Django 4.0.6 on 2022-08-14 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceRegistrar', '0013_deviceregistry_lastcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLastUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastContact', models.TimeField(null=True)),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DeviceRegistrar.deviceregistry')),
            ],
        ),
    ]
