# Generated by Django 4.0.6 on 2022-08-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceRegistrar', '0014_devicelastupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceregistry',
            name='LastContact',
        ),
    ]
