# Generated by Django 4.0.6 on 2022-10-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RollNo', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=50)),
            ],
        ),
    ]
